apiVersion: v1
kind: PersistentVolume
metadata:
 name: mailing-storage1
spec:
 accessModes:
 - ReadWriteOnce
 capacity:
   storage: 5Gi
 storageClassName: gp2
 hostPath:
   path: /home/ubuntu/mailing
 persistentVolumeReclaimPolicy: Retain
 
