apiVersion: v1
kind: PersistentVolume
metadata:
 name: simple1
spec:
 accessModes:
 - ReadWriteOnce
 capacity:
   storage: 1Gi
 storageClassName: gp2
 hostPath:
   path: /home/ubuntu/simple
 persistentVolumeReclaimPolicy: Retain
